version: "3"

networks:
  gift.net:
    driver: bridge

services:
  app:
    image: canals/php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128

    ports:
      - "15081:80"
      - "15444:443"
    volumes :
      - ./gift.appli/public:/var/www/html
      - ./shared/img:/var/www/html/img
      - ./gift.appli/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - gift.net
    depends_on:
      - sql
  visit:
    image: canals/php:latest
    ports:
      - "15181:80"
      - "15544:443"
    volumes :
      - ./gift.visit/public:/var/www/html
      - ./gift.visit/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - gift.net
    depends_on:
      - sql
  api:
    image: canals/php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128

    ports:
      - "15281:80"
      - "15644:443"
    volumes :
      - ./gift.api/public:/var/www/html
      - ./gift.api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - gift.net
    depends_on:
      - sql

  back:
    image: canals/php:latest
    ports:
      - "15381:80"
      - "15744:443"
    volumes :
      - ./gift.back/public:/var/www/html
      - ./gift.back/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - gift.net
    depends_on:
      - sql



  #############################
  # mysql + adminer / can be replaced by mariadb
  #############################
  sql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gift
      - MYSQL_USER=gift
      - MYSQL_PASSWORD=gift
    ports:
      - "3606:3306"
    networks:
      gift.net:
        aliases:
          - sql.db

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - gift.net



##################################
# postgres + adminer
###################################
# postgres:
#   image: postgres
#   environment :
#   - POSTGRES_PASSWORD=pgroot
#   - POSTGRES_USER=pguser
#   ports:
#   - "5432:5432"
#   networks:
#   - local_network




########################################
# shared storage : useful for, e.g. sharing
#   uploaded documents (img, others) between multiple services
########################################
#volumes:
#   data:
